version: '3.8'

services:
  web:
    build:
      context: ./web
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  worker:
    build: ./worker
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: "redis:alpine"
    healthcheck:
      test: ["CMD","redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5